fileVersion: 1
id: "2"
mappingDefinitions:
  CALENDARS_FOR_FINANCE_AND_ANALYTICS:
    database: CALENDARS_FOR_FINANCE_AND_ANALYTICS
    schema: PUBLIC
  NETSUITE_PREPARED:
    database: PINSLY_PREPARED_PROD
    schema: NETSUITE_PREPARED
  NETSUITE_RAW:
    database: PINSLY_RAW
    schema: NETSUITE_SUITEANALYTICS
  OPERATIONS_MODEL_PREPARED:
    database: PINSLY_PREPARED_PROD
    schema: OPERATIONS_MODEL_PREPARED
  SAFETRACK_PREPARED:
    database: PINSLY_PREPARED_PROD
    schema: SAFETRACK_PREPARED
  SAFETRACK_RAW:
    database: PINSLY_RAW
    schema: PUBLIC
  SHAREPOINT_RAW:
    database: PINSLY_RAW_DEV
    schema: SHAREPOINT
  WABTEC_PREPARED:
    database: PINSLY_PREPARED_PROD
    schema: WABTEC_PREPARED
  WABTEC_RAW:
    database: PINSLY_RAW_DEV
    schema: WABTEC
name: Production
type: Environment
